version: "3.3"

services:
  rapidog-db:
    image: app-db
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - "5434:5432"
    env_file:
      - composer.env
    volumes:
      - db_rapidog:/var/lib/postgresql/data
    networks:
      - rapidog

  web-app:
    depends_on:
      - rapidog-db
    image: web-app
    build:
      context: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - composer.env
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3000:8000
    networks:
      - rapidog

volumes:
  db_rapidog:
networks:
  rapidog: